%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "Rectified"

# Rectified Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 382.613
Camera1.fy: 382.613
Camera1.cx: 320.183
Camera1.cy: 236.455

Stereo.b: 0.0499585
# Camera resolution
Camera.width: 640
Camera.height: 480
# Camera frames per second
Camera.fps: 30
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1
# Close/Far threshold. Baseline times.
Stereo.ThDepth: 30.0
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image - REDUCED for faster processing
ORBextractor.nFeatures: 750
# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2
# ORB Extractor: Number of levels in the scale pyramid - REDUCED for faster processing
ORBextractor.nLevels: 6
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 18
ORBextractor.minThFAST: 5
#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
#--------------------------------------------------------------------------------------------
# Performance Parameters
#--------------------------------------------------------------------------------------------
# Maximum number of tracked points (lower = faster)
ORBextractor.maxTrackedPoints: 500
# Culling factor (discard keypoints that are more than this factor times the median distance)
ORBextractor.cullingFactor: 1.2
# Map point creation interval (frames)
System.mapPointCreationInterval: 2
# Local mapping on/off (set true during exploration, false during high-speed navigation)
System.EnableLocalMapping: true
# Loop closing on/off (set true for map correction, false for pure odometry)
System.EnableLoopClosing: false
# Parallel threads (set according to your CPU)
System.nThreads: 4

